<?php

namespace MediasBundle\Repository;

/**
 * MediaTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MediaTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
