<?php

namespace MediasBundle\Repository;

/**
 * Type_mediaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Type_mediaRepository extends \Doctrine\ORM\EntityRepository
{
}
