db:
    image: mysql
    volumes:
        - /var/lib/boot2docker/mysql:/var/lib/mysql
        - /var/www/docker/maestro/conf:/etc/mysql/conf.d
    environment:
        - MYSQL_ROOT_PASSWORD=root
    ports:
        - "3306:3306"

apache:
    image: eboraas/apache
    ports:
        - "80:80"
        - "443:443"
    volumes:
        - /var/www/Maestro:/var/www/maestro
        - /var/www/docker/maestro/conf/php.ini:/etc/php5/apache2/conf.d/30-custom.ini
        - /var/www/docker/maestro/conf/sites:/etc/apache2/sites-enabled
    environment:
        - ALLOW_OVERRIDE=true 
    links:
        - db:db

